create table if not exists public.telegram_bot_updates (
  id bigint generated by default as identity primary key,
  update_id bigint unique,
  telegram_user_id bigint references public.telegram_bot_users(telegram_user_id) on delete set null,
  chat_id bigint,
  message_id bigint,
  update_type text not null,
  text text,
  payload jsonb not null default '{}'::jsonb,
  received_at timestamptz not null default now()
);

create index if not exists telegram_bot_updates_user_received_idx
  on public.telegram_bot_updates (telegram_user_id, received_at desc);

create index if not exists telegram_bot_updates_chat_received_idx
  on public.telegram_bot_updates (chat_id, received_at desc);

create index if not exists telegram_bot_updates_type_received_idx
  on public.telegram_bot_updates (update_type, received_at desc);

alter table public.telegram_bot_updates enable row level security;

create policy telegram_bot_updates_private_deny
on public.telegram_bot_updates
as restrictive
for all
to anon, authenticated
using (false)
with check (false);
